import json

f = open("mapa.json")
bd = json.load(f)
f.close

ttl = f"""
@prefix : <http://rpcw.di.uminho.pt/2024/mapa/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://rpcw.di.uminho.pt/2024/mapa/> .

<http://rpcw.di.uminho.pt/2024/mapa> rdf:type owl:Ontology .

#################################################################
#    Object Properties
#################################################################

###  http://rpcw.di.uminho.pt/2024/mapa#destinoLigacao
:destinoLigacao rdf:type owl:ObjectProperty ;
                rdfs:domain :Ligacao ;
                rdfs:range :Cidade .


###  http://rpcw.di.uminho.pt/2024/mapa#origemLigacao
:origemLigacao rdf:type owl:ObjectProperty ;
               rdfs:domain :Ligacao ;
               rdfs:range :Cidade .


#################################################################
#    Data properties
#################################################################

###  http://rpcw.di.uminho.pt/2024/mapa#descricao
:descricao rdf:type owl:DatatypeProperty ;
           rdfs:domain :Cidade ;
           rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/mapa#distancia
:distancia rdf:type owl:DatatypeProperty ;
           rdfs:domain :Ligacao ;
           rdfs:range xsd:int .


###  http://rpcw.di.uminho.pt/2024/mapa#distrito
:distrito rdf:type owl:DatatypeProperty ;
          rdfs:domain :Cidade ;
          rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/mapa#idCidade
:idCidade rdf:type owl:DatatypeProperty ;
          rdfs:domain :Cidade ;
          rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/mapa#idLigacao
:idLigacao rdf:type owl:DatatypeProperty ;
           rdfs:domain :Ligacao ;
           rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/mapa#nome
:nome rdf:type owl:DatatypeProperty ;
      rdfs:domain :Cidade ;
      rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/mapa#populacao
:populacao rdf:type owl:DatatypeProperty ;
           rdfs:domain :Cidade ;
           rdfs:range xsd:int .


#################################################################
#    Classes
#################################################################

###  http://rpcw.di.uminho.pt/2024/mapa#Cidade
:Cidade rdf:type owl:Class .


###  http://rpcw.di.uminho.pt/2024/mapa#Ligacao
:Ligacao rdf:type owl:Class .


#################################################################
#    Individuals
#################################################################

"""

for cidade in bd['cidades']:
    registo = f"""
    ###  http://rpcw.di.uminho.pt/2024/mapa##{cidade['id']}
    :{cidade['id']} rdf:type owl:NamedIndividual,
                :Cidade ;
                :descricao "{cidade['descrição']}" ;
                :distrito "{cidade['distrito']}" ;
                :idCidade "{cidade['id']}" ;
                :nome "{cidade['nome']}" ;
                :populacao {cidade['população']} .
"""
    ttl += registo

for ligacao in bd['ligacoes']:
    registo = f"""
    ###  http://rpcw.di.uminho.pt/2024/mapa##{ligacao['id']}
    :{ligacao['id']} rdf:type owl:NamedIndividual,
                :Ligacao ;
                :destinoLigacao :{ligacao['destino']} ;
                :origemLigacao :{ligacao['origem']} ;
                :distancia {ligacao['distância']} ;
                :idLigacao "{ligacao['id']}" .
"""
    ttl += registo



ttl += f"""###  Generated by the OWL API (version 4.5.26.2023-07-17T20:34:13Z) https://github.com/owlcs/owlapi"""

output = open("mapa_povoado.ttl", "w")
output.write(ttl)
