import json

f = open("db-musica.json")
bd = json.load(f)
f.close

ttl = f"""
@prefix : <http://rpcw.di.uminho.pt/2024/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://rpcw.di.uminho.pt/2024/> .

<http://rpcw.di.uminho.pt/2024/musica> rdf:type owl:Ontology .

#################################################################
#    Object Properties
#################################################################

###  http://rpcw.di.uminho.pt/2024/musica#ensinaIntrumento
:ensinaIntrumento rdf:type owl:ObjectProperty ;
                  rdfs:domain :Curso ;
                  rdfs:range :Instrumento .


###  http://rpcw.di.uminho.pt/2024/musica#temCurso
:temCurso rdf:type owl:ObjectProperty ;
          rdfs:domain :Aluno ;
          rdfs:range :Curso .


###  http://rpcw.di.uminho.pt/2024/musica#tocaIntrumento
:tocaIntrumento rdf:type owl:ObjectProperty ;
                rdfs:domain :Aluno ;
                rdfs:range :Instrumento .


#################################################################
#    Data properties
#################################################################

###  http://rpcw.di.uminho.pt/2024/musica#ano
:ano rdf:type owl:DatatypeProperty ;
     rdfs:domain :Aluno ;
     rdfs:range xsd:int .


###  http://rpcw.di.uminho.pt/2024/musica#dataNasc
:dataNasc rdf:type owl:DatatypeProperty ;
          rdfs:domain :Aluno ;
          rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/musica#duracao
:duracao rdf:type owl:DatatypeProperty ;
         rdfs:domain :Curso ;
         rdfs:range xsd:int .


###  http://rpcw.di.uminho.pt/2024/musica#idAluno
:idAluno rdf:type owl:DatatypeProperty ;
         rdfs:domain :Aluno ;
         rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/musica#idCurso
:idCurso rdf:type owl:DatatypeProperty ;
         rdfs:domain :Curso ;
         rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/musica#idIntrumento
:idIntrumento rdf:type owl:DatatypeProperty ;
              rdfs:domain :Instrumento ;
              rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/musica#nome
:nome rdf:type owl:DatatypeProperty ;
      rdfs:domain :Aluno ;
      rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/musica#nomeCurso
:nomeCurso rdf:type owl:DatatypeProperty ;
           rdfs:domain :Curso ;
           rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/musica#nomeIntrumento
:nomeIntrumento rdf:type owl:DatatypeProperty ;
                rdfs:domain :Instrumento ;
                rdfs:range xsd:string .


#################################################################
#    Classes
#################################################################

###  http://rpcw.di.uminho.pt/2024/musica#Aluno
:Aluno rdf:type owl:Class .


###  http://rpcw.di.uminho.pt/2024/musica#Curso
:Curso rdf:type owl:Class .


###  http://rpcw.di.uminho.pt/2024/musica#Instrumento
:Instrumento rdf:type owl:Class .

#################################################################
#    Individuals
#################################################################

"""

for aluno in bd['alunos']:
    registo = f"""
    ###  http://rpcw.di.uminho.pt/2024/musica#{aluno['id']}
    :{aluno['id']} rdf:type owl:NamedIndividual ,
                 :Aluno ;
                 :temCurso :{aluno['curso']} ;
                 :tocaIntrumento :{aluno['instrumento']} ;
                 :ano {aluno['anoCurso']} ;
                 :dataNasc "{aluno['dataNasc']}" ;
                 :idAluno "{aluno['id']}" ;
                 :nome "{aluno['nome']}" .


"""
    ttl += registo

for curso in bd['cursos']:
    registo = f"""
    ###  http://rpcw.di.uminho.pt/2024/musica#{curso['id']}
    :{curso['id']} rdf:type owl:NamedIndividual ,
              :Curso ;
              :ensinaIntrumento : {curso['instrumento']};
              :duracao {curso['duracao']} ;
              :idCurso "{curso['id']}";
              :nomeCurso "{curso['designacao']}" .

"""
    ttl += registo

for instrumento in bd['instrumentos']:
    registo = f"""
    ###  http://rpcw.di.uminho.pt/2024/musica#{instrumento['id']}
    :{instrumento['id']} rdf:type owl:NamedIndividual ,
             :Instrumento ;
             :idIntrumento "{instrumento['id']}" ;
             :nomeIntrumento ""{instrumento['#text']}" .


"""
    ttl += registo

ttl += f"""###  Generated by the OWL API (version 4.5.26.2023-07-17T20:34:13Z) https://github.com/owlcs/owlapi"""

output = open("musica_povoada.ttl", "w")
output.write(ttl)
